# Generated by Django 2.2.6 on 2019-12-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('prediction', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('is_correct', models.BooleanField(null=True)),
                ('other_predictions', models.TextField()),
            ],
        ),
    ]
